### Numpy

In [ ]:
!pip install numpy

In [1]:
import numpy as np

## Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

- NumPy is a Open Source Python package. It stands for **Numerical Python**. 
It is a library consisting of multidimensional array objects and 
a collection of routines for processing of array.

In [2]:
import time as tm

size_1 = 1000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 0.6232001781463623
numpy = 0.01133871078491211


In [6]:
my_list=[2,3,4,6,7,8]

In [7]:
my_list

[2, 3, 4, 6, 7, 8]

In [4]:
aar = np.array(my_list)

In [5]:
aar

array([2, 3, 4, 6, 7, 8])

In [8]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [10]:
array_3.ndim

2

In [11]:
array_3.size

9

In [13]:
array_3.max()

9

In [14]:
array_3.min()

1

In [19]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [20]:
a = np.array([1, 2, 3, 4], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [22]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
array_3[2]

array([7, 8, 9])

In [23]:
array_3[0]

array([1, 2, 3])

In [24]:
array_3[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_3[1:2]

array([[4, 5, 6]])

In [26]:
array_3[:,1]

array([2, 5, 8])

In [27]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [31]:
np.zeros([2,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
np.eye(3,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [39]:
np.linspace(-10, 1, 12)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.])

In [40]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [43]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [44]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [45]:
x.reshape(1,16)

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13]])

In [46]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [47]:
x.max()

13

In [48]:
x.min()

1

In [49]:
x.mean()

7.0

In [50]:
x.std()

3.5355339059327378

In [51]:
x.var()

12.5

In [52]:
x.sum()

112

In [53]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [54]:
x.min()

1

In [55]:
x.min(axis=0)

array([1, 2, 3, 4])

In [56]:
x.min(axis=1)

array([ 1,  4,  7, 10])

In [57]:
x.max(axis=1)

array([ 4,  7, 10, 13])

In [58]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [59]:
x.mean(axis=0)

array([5.5, 6.5, 7.5, 8.5])

In [60]:
x.mean(axis=1)

array([ 2.5,  5.5,  8.5, 11.5])

In [61]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [62]:
x.argmin()

0

In [63]:
x.argmax()

15

In [64]:
X = x.flatten()

In [65]:
X

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [66]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [67]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [68]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [69]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [70]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
A+B

array([[ 5., 11., 12.],
       [22., 23., 24.],
       [32., 33., 34.]])

In [72]:
A-B

array([[ 3.,  9., 10.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [73]:
A/B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [74]:
A%B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
A*B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [76]:
A**2

array([[  16,  100,  121],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [77]:
A/3

array([[ 1.33333333,  3.33333333,  3.66666667],
       [ 7.        ,  7.33333333,  7.66666667],
       [10.33333333, 10.66666667, 11.        ]])

In [79]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [80]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.dot(A,B)

array([[25., 25., 25.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [81]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [82]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [83]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [84]:
a=np.array([[11.667,23.662],[33.21,45.887]])

In [85]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [86]:
np.around(a)

array([[12., 24.],
       [33., 46.]])

In [87]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [88]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.concatenate([A,B])

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [94]:
np.random.randint(2,9,(3,4))

array([[7, 6, 3, 3],
       [2, 4, 2, 7],
       [2, 2, 6, 5]])

In [91]:
np.random.rand(3,4)

array([[0.65677069, 0.51168231, 0.03034794, 0.96543447],
       [0.13855784, 0.29386686, 0.77826652, 0.30891905],
       [0.58056901, 0.99955928, 0.70580342, 0.4742628 ]])

In [95]:
np.random.randn(4,4)

array([[ 0.25004816,  1.33588815, -0.07364825, -0.85869547],
       [-0.68683341,  0.31061591,  0.80879076, -1.18323419],
       [-0.82725509, -0.45133674,  0.55373236, -0.09120607],
       [-1.10728843,  0.74497977, -0.46574695,  0.81287044]])